### PR TITLE
Get subnet from local ipv4 adress

### PR DESCRIPTION
**Pull request by sistr22**
Hi !
Thx for the app !
It works much better than the official one but my subnet is 192.168.0.XX so I had to manually enter the IP adress of the kettle.
I fixed the issue now, feel free to merge if you want or discard the pull request, I won't mind :)

### CODE REVIEW

**Comment by ian-kent** [comment]
awesome, thanks @Whiteseeker - spotted the bug shortly after publishing to google play but haven't had a chance to fix! I'll publish an update with your fix to google play asap!

**Comment by sistr22** [comment]
Ideally we should check the network mask (like 255.255.255.0) too. Right
now we assume it's that value but if you are using a company wifi, it might
be 255.255.0.0 and thus we would need to check ... well 255 time more
address ^^ It might get unmanageable :/

**Comment by ian-kent** [comment]
> well 255 time more
> address ^^ It might get unmanageable

kinda where I got to with it :smile:

i'm planning on improving that screen, adding advanced options e.g. which subnets/IP ranges to scan, hopefully that might help a bit!

I can't think of any easy solution though :cry: the official app uses UDP broadcast, but based on their Google Play comments (and my own experience) that doesn't seem to work all that well!

**Comment by sistr22** [comment]
Well personally I feel:
- Any "normal" user should have a mask like "255.255.255.0" -> current
  solution is perfect
- If the mask is like 255.255.0.0 -> We try like if it was
  255.255.255.0, if it doesn't works we display a nice message saying that
  the network configuration is unusual and we can't detect the kettle
  automatically, and we let the user enter the ip address manually if he
  wants (as currently).
  That's fine I think.
  It's probably better to focus on the 95% usecase than on the 5% left.
  And add more features :)

**Pull request merged**
